### PR TITLE
python-social-auth version update PR

### PR DESCRIPTION
**Pull request by cmltaWt0**
@dixon-che 

This PR contain version update for python-social-auth.

python-social-auth version was freezed to 0.2.9 because of [issue](https://github.com/omab/python-social-auth/issues/671).
This issue was fixed in [PR](https://github.com/omab/python-social-auth/pull/672) and have appeared in 0.2.12 version.
So now we can move to python-social-auth 0.2.12 version.

Task for this PR on [trello](https://trello.com/c/YR7uBK85/185-review-new-psa-0-2-12-version).

### CODE REVIEW

**Comment by auraz** [comment]
please test manually, then :+1:

**Comment by cmltaWt0** [comment]
> please test manually, then

it was tested manually on local machine and on development server. 
:+1:

**Comment by auraz** [comment]
Thanks

**Comment by dixon-che** [comment]
Reviewed

**Pull request closed without merging**
